openshift_clusters:
  - api_url: "https://api.san01.san.pre.bo1.paas.cloudcenter.corp:8443"
    environment: "PRE"
    region: "BO1"
    token: ""
  - api_url: "https://api.san01bks.san.pre.bo1.paas.cloudcenter.corp:6443"
    environment: "PRE"
    region: "BO1"
    token: ""    
  - api_url: "https://api.ocp01.san.pre.weu1.azure.paas.cloudcenter.corp:6443"
    environment: "PRE"
    region: "WEU1"
    token: ""
  - api_url: "https://api.san01.san.dev.bo1.paas.cloudcenter.corp:8443"
    environment: "DEV"
    region: "BO1"
    token: ""
